---
- name: Configure Metronome Kubernetes Server
  hosts: metronome
  become: true

  tasks:

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Ensure kubectl is installed
      command: snap install kubectl --classic
      register: kubectl_install
      failed_when:
        - kubectl_install.rc != 0
        - "'already installed' not in kubectl_install.stdout"
      changed_when: kubectl_install.rc == 0

    - name: Ensure K3s service is running
      systemd:
        name: k3s
        enabled: true
        state: started

    - name: Check Kubernetes cluster
      command: kubectl get nodes
      environment:
        KUBECONFIG: /home/devops/.kube/config
      register: kubernetes_nodes
      changed_when: false

    - name: Display Kubernetes nodes
      debug:
        var: kubernetes_nodes.stdout
